### ISSUE TITLE
[bug] reqKick throws error on boot up

### ISSUE THREAD

**Issue by scriptnull** [Shippable/kermit-nodeInit#31]
https://github.com/Shippable/pm/issues/12306

```

Error: Cannot find module 'C:\Users\Administrator\Shippable\reqKick\reqKick.app.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
module.js:549
    throw err;
    ^
```

Fixing it we face

```

PS C:\Users\Administrator\AppData\Local\Temp> cat  shippable-reqkick-eb61041d-60db-4557-9d9a-a2c0d37181a5.err

2019-05-15T12:11:04.665Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:11:07.277Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:11:11.845Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:11:20.425Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:11:36.990Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:12:09.617Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:13:14.199Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:15:22.806Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:17:31.377Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:18:48.607Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:18:51.182Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:18:55.771Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:19:04.318Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:19:20.901Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
2019-05-15T12:19:53.474Z - error: reqKick|reqKick.app.js: Missing ENV: NODE_TYPE_CODE
PS C:\Users\Administrator\AppData\Local\Temp> nssm get shippable-reqkick-eb61041d-60db-4557-9d9a-a2c0d37181a5 "AppEnvironmentExtra"
STATUS_DIR=C:\Users\Administrator\Shippable\Runtime\eb61041d-60db-4557-9d9a-a2c0d37181a5\build\status
SCRIPTS_DIR=C:\Users\Administrator\Shippable\Runtime\eb61041d-60db-4557-9d9a-a2c0d37181a5\build\scripts
RUN_MODE=devmode
REQEXEC_BIN_PATH=C:\Users\Administrator\Shippable\Runtime\eb61041d-60db-4557-9d9a-a2c0d37181a5\reqExec\x86_64\WindowsServer_2019\dist\main\main.exe
NODE_ID=16
SUBSCRIPTION_ID=
NODE_TYPE_CODE=7000
SHIPPABLE_NODE_ARCHITECTURE=x86_64
SHIPPABLE_NODE_OPERATING_SYSTEM=WindowsServer_2019
SHIPPABLE_API_URL=http://1bbf1517.ngrok.io
```

**Comment by scriptnull** [comment]
Reqkick boots up successfully

![image](https://user-images.githubusercontent.com/4211715/57778943-c77e4980-7742-11e9-9f79-bf35c6f2beeb.png)
